### ISSUE TITLE
Chap 6: exptData is not defined

### ISSUE THREAD

**Issue by htluandc2** [mhtess/webppl-tutorials#3]
Hi there, I learn on your course about BDA using Probabilistic Programming. In chapter 6, I met this error: 
`exptData is not defined
ReferenceError: exptData is not defined
    at eval (eval at run (https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1006097), <anonymous>:234:42)
    at f (https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1064693)
    at https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1005370
    at https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1005370
    at https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1005370
    at runner (https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1005532)
    at eval (eval at run (https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1006097), <anonymous>:5:17)
    at https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1006541
    at next (https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1019649)
    at Object.getParams (https://s3-us-west-2.amazonaws.com/cdn.webppl.org/webppl-v0.9.13.js:1:1024185)`

Really your course is very simple and great.Thank you for your course.

**Comment by mhtess** [comment]
Hi there. Thanks for your interest in the course. I haven't yet ported over all of the chapter materials from an earlier version of the course, but you should be able to find the same content for this chapter here:
https://mhtess.github.io/bdappl2018/chapters/5-advancedBDA.html

Sorry for the inconvenience, and glad to hear you have these materials helpful
